### ISSUE TITLE
Build fails for arm64 because of pip3

### ISSUE THREAD

**Issue by sfudeus** [sfudeus/homematic_exporter#19]
Seemingly, python:3-slim-buster for arm64 does not contain pip3, so the build failed:
```
#10 0.995 /usr/local/bin/python: can't open file '//pip3': [Errno 2] No such file or directory
```
Need to investigate.
/cc @mrueg 

This was introduced through #17

**Comment by mrueg** [comment]
This is interesting. I would expect them to behave the same on every arch since they seem to be build from a single source https://github.com/docker-library/python

I checked the arm64 image and pip is there: 
```
# ls -lisa /usr/local/bin/pip* 
1176866 4 -rwxr-xr-x 1 root root 226 Feb  9 15:37 /usr/local/bin/pip
1176867 4 -rwxr-xr-x 1 root root 226 Feb  9 15:37 /usr/local/bin/pip3
1176868 4 -rwxr-xr-x 1 root root 226 Feb  9 15:37 /usr/local/bin/pip3.9
```

**Comment by mrueg** [comment]
@sfudeus can you reproduce locally?

**Comment by sfudeus** [comment]
No, works for me locally. Maybe an old copy of the moving tag 3-slim-buster was used? I'll retrigger and see.
Local test used  
```
docker.io/library/python:3-slim-buster@sha256:bf3ec573c0ae0d0c619c3f3e0e9490878432bf7a5c63a643b6c39c9878b51191

**Comment by sfudeus** [comment]
The broken one on github used
```
#9 [linux/arm64 1/3] FROM docker.io/library/python:3-slim-buster@sha256:bf3ec573c0ae0d0c619c3f3e0e9490878432bf7a5c63a643b6c39c9878b51191

Which looks identical - wtf?

**Comment by sfudeus** [comment]
Worked this time when retriggering - so maybe a onetime glitch on the buildhost or qemu issue. Still slightly weird.
