### ISSUE TITLE
Support authentication

### ISSUE THREAD

**Issue by NilsGriebner** [sfudeus/homematic_exporter#23]
Hi,

API endpoints are secured by default. After upgrading my CCU 3 I had to manually disable authentication. Would it be possible to support authenticated connection?

**Comment by sfudeus** [comment]
Will check

**Comment by sfudeus** [comment]
should be solved with #24

**Comment by NilsGriebner** [comment]
Thanks for implementing this. I'll check it out in the next few days.

**Comment by sfudeus** [comment]
workforme at least, this closing
