### ISSUE TITLE
config parameters as enviroment variables

### ISSUE THREAD

**Issue by DanielWeeber** [sfudeus/homematic_exporter#33]
parameters for /usr/local/homematic_exporter (esp. "ccu_host") should be configurable via enviroment variables

would be better/easier/more usual for running as a docker

**Comment by sfudeus** [comment]
Agreed - unfortunately the Python library I am using does not have support for initializing cli args based on environment variables. Setting defaults from env would have the drawback of losing the explicit definition of `required` arguments.

**Comment by sfudeus** [comment]
Was just requested again as #61, and I quickly added support for it. Was easier than expected, sorry that it took that long. Happy testing.

**Comment by sfudeus** [comment]
fixed by #62
