### ISSUE TITLE
Allow passing the CCU_* config options via ENV vars

### ISSUE THREAD

**Issue by fbrnc** [sfudeus/homematic_exporter#61]
Hello,

thank you so much for this exporter! I'm using it via Docker Compose and my Homematic instance has auth enabled. 
I'd like to avoid overwriting the entrypoint in the docker-compose.yaml

entrypoint: [ 
      "/usr/local/bin/homematic_exporter", 
      "--ccu_host", "...", 
      "--ccu_port", "...", 
      "--ccu_user", "...", 
      "--ccu_pass", "..."
    ]

Specifically I'd like to avoid embedding the credentials in the docker-compose file. I'd rather pass them via environment variables and including them via "env_file" so I can exlude that file from version control.

I'm happy to provide a merge request if you'd consider this a useful enhancement.

**Comment by sfudeus** [comment]
No need to overwrite the entrypoint I think, you could pass them as command args, but that's not much of a difference with the trivial default entrypoint definition. 
I get your point about credentials (which aren't that good via env variables as well). I'll soonish add support for defining the cli args via environment.

**Comment by sfudeus** [comment]
Feel free to test docker.io/sfudeus/homematic_exporter:preview-62, it should have all you need I think.

**Comment by fbrnc** [comment]
Works like a charm! Thank you so much. This is exactly what I needed. Thank you :)

**Comment by sfudeus** [comment]
thx, for the feedback, merging now
